### ISSUE TITLE
Terminate threads after simulation to reduce CPU load

### ISSUE THREAD

**Issue by MicheleMUC** [BauhausLuftfahrt/PAXelerate#1]

**Comment by RRothfeld** [comment]
Threads können per .stop() Funktion gestoppt werden. Das ist aber veraltet, mittlerweile einfach Thread = null; setzten.

Trennung von GUI und Prozessen (also Freihaltung des [event dispatch threads](https://en.wikipedia.org/wiki/Event_dispatching_thread)) à la SwingWorker:
1. SwingWorker (SW) wird via GUI interaction aufgerufen und gestartet (execute())
2. SW arbeitet aufwendingen Prozess ab, welcher in doInBackground() im SW definiert wird.
3. Innerhalb der doInBackground()-Funktion wird die SW-eigene Funktion publish() aufgerufen immer wenn es ein Zwischenergebnis gibt (z.B. eine Zahl oder ein Wort)
4. Jedes mal wenn publish() aufgerufen wird, wird der darin entsandte Wert einer Liste hinzugefügt.
5. Sporadisch wird die Rechenkraft vom aufwendigen doInBackground()-Prozess auf die GUI geleitet um diese upzudaten (mehrfach pro Sekunde). Immer wenn das geschieht, wird die process()-Funktion des SW aufgerufen, welche Zugriff auf die durch publish() gefüllte Liste hat. Innerhalb der process()-Funktion kann man dann die GUI updaten lassen mit den neuesten Wert, oder allen gespeicherten Zwischenwerten, etc.
6. Der SW beendet sich selbst, sobald kein Rechenbedarf mehr besteht

Zum reinlesen: https://docs.oracle.com/javase/tutorial/uiswing/concurrency/interim.html oder die volle Dokumentation https://docs.oracle.com/javase/7/docs/api/javax/swing/SwingWorker.html

Da wir nicht Swing benutzten sondern Eclipses' eigenes Front-End müssten wir Michael Sh. fragen wie es dort geht.

**Comment by MicheleMUC** [comment]
@MSH check what oppurtunities Eclipse provides

**Comment by RRothfeld** [comment]
Marc, bitte die Funktion stopSimulation() in SimulationHandler erarbeiten, dann sollte diese Issue auch erledigt sein.
