### ISSUE TITLE
Model Explorer: Define meaning of exclamation points

### ISSUE THREAD

**Issue by MicheleMUC** [BauhausLuftfahrt/PAXelerate#37]
Tracebility of errors or warning in model explorer

**Comment by marcengelmann** [comment]
Meaning is explained when hovering above the exclamation mark. 
![unbenannt](https://cloud.githubusercontent.com/assets/16258698/13741322/ecac6b54-e9d5-11e5-8b52-80ecf6b6eae1.PNG)

**Comment by marcengelmann** [comment]
BUT warning Symbol at cabin Icon currently unjustified

**Comment by MicheleMUC** [comment]
![warning](https://cloud.githubusercontent.com/assets/17379697/13741418/80b7520a-e9d6-11e5-9585-9a5a643225be.png)

Excatly what I mean: no clue why a warnign symbol is shown
