### ISSUE TITLE
Introduce CabinAdapter in net.bhl....core

### ISSUE THREAD

**Issue by MicheleMUC** [BauhausLuftfahrt/PAXelerate#58]

**Comment by MicheleMUC** [comment]
@RRothfeld Can you please provide a short description? Thx

**Comment by RRothfeld** [comment]
Einführung einer Trennklasse zwischen Core-Klassen und der eigentlichen Cabin (Model). Damit keine Klasse mehr direkt auf die Cabin zugreift.
