### ISSUE TITLE
Import/Export project function does not load *.esp files

### ISSUE THREAD

**Issue by MicheleMUC** [BauhausLuftfahrt/PAXelerate#67]
Models are saved as *.xmi files and projects as *.esp; however, the project import function only allows to open *.xmi files.

**Comment by MicheleMUC** [comment]
![project](https://cloud.githubusercontent.com/assets/17379697/13257845/be6a3fee-da50-11e5-9e6f-d5149ffd706f.png)

**Comment by MicheleMUC** [comment]
@marcengelmann: could you test that on your system as well. Thx

**Comment by marcengelmann** [comment]
@MicheleMUC  same here

**Comment by MicheleMUC** [comment]
WIP: discussion with MSh - OpenCDT

**Comment by MicheleMUC** [comment]
EMF specific error --> won't fix
