### ISSUE TITLE
On first startup, model elements are not listed (new model element menu is empty!)

### ISSUE THREAD

**Issue by marcengelmann** [BauhausLuftfahrt/PAXelerate#83]

**Comment by MicheleMUC** [comment]
@marcengelmann I can't reproduce, PAXelerate related are sorted and available. Try to clean the workspace, delete `.cdt` folder and delete all `paxelerate.product` folders

**Comment by marcengelmann** [comment]
@MicheleMUC  did it, still there

**Comment by marcengelmann** [comment]
@MicheleMUC it works on a different PC, so issue is with the other PC :+1:
