### ISSUE TITLE
Right Click menu with "generate pax" & "simulate" is shown on every element and folder 

### ISSUE THREAD

**Issue by marcengelmann** [BauhausLuftfahrt/PAXelerate#84]
.. but it should only be shown when right-clicking on the cabin element

**Comment by MicheleMUC** [comment]
@marcengelmann I can't reproduce, PAXelerate related are sorted and available. Try to clean the workspace, delete `.cdt` folder and delete all `paxelerate.product` folders.

![right-click](https://cloud.githubusercontent.com/assets/17379697/13809661/11136a50-eb6c-11e5-8173-39c75de8b01a.png)

**Comment by marcengelmann** [comment]
seems to be solved
